title: "Sarah Van Wart"
email: svanwart@unca.edu
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

timezone: "America/New_York"
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude: 
  - _lectures/draft
  - _assignments/draft
  - pages/draft
  - course-files/administrative
  - course-files/build
  - course-files/homework/drafts
  - course-files/tutorials/drafts
  - course-files/lectures/drafts
  - course-files/practice_exams/drafts
  - course-files/projects/drafts
collections:
  resources:
    output: true
    sort_by: lecture_date
    permalink: /resources/:name

collections_dir: pages

sass:
  style: compact
  sass_dir: _sass